/* Generated by cbindgen from crates/loom-engine-capi/src/lib.rs.
 * Do not edit by hand -- run `cbindgen --config cbindgen.toml --crate loom-engine-capi --output include/loom.h`
 * from this directory after changing the Rust API, and commit the result. */


#ifndef LOOM_ENGINE_CAPI_H
#define LOOM_ENGINE_CAPI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Game identifiers for `loom_create`. Must stay in sync with
 * `loom_engine::game::GameId` -- see `game_id_from_u32` below, the one
 * place that mapping is defined.
 */
#define LOOM_GAME_KNIT 0

#define LOOM_GAME_MATCH3 1

#define LOOM_GAME_MERGE2 2

#define LOOM_GAME_PICROSS 3

/**
 * Opaque handle to a running `Shell<G>` instance, for one of the 4 games.
 */
typedef struct LoomHandle LoomHandle;

/**
 * Create a new game instance. `game_id` is one of the `LOOM_GAME_*`
 * constants. Loads real persisted settings/campaign/high-score state from
 * disk (same location the native terminal build uses for that game).
 * Returns null if `game_id` is unrecognized.
 *
 * # Safety
 * The returned pointer, if non-null, must eventually be passed to exactly
 * one `loom_destroy` call and to no other function after that.
 */
 struct LoomHandle *loom_create(uint32_t game_id);

/**
 * Destroy a handle created by `loom_create`. Does *not* call
 * `loom_save_on_exit` implicitly -- call that first if the in-progress
 * campaign run should be persisted.
 *
 * # Safety
 * `handle` must be a pointer previously returned by `loom_create` and not
 * already destroyed. Passing null is safe (no-op).
 */
 void loom_destroy(struct LoomHandle *handle);

/**
 * Handle one key event, JSON-encoded as `loom_engine::input::KeyEvent`.
 * `key` is either a plain string for the 6 non-character keys --
 * `"Up"`/`"Down"`/`"Left"`/`"Right"`/`"Enter"`/`"Esc"` -- or
 * `{"Char":"a"}` for a character key. `mods` is `""` for no modifiers, or
 * bitflags' `serde` string format for combinations, e.g. `"CTRL | SHIFT"`
 * (note: no game currently reads modifiers on any key, so `""` always
 * works in practice). Examples:
 * `{"key":"Up","mods":""}`, `{"key":{"Char":"a"},"mods":""}`.
 * Returns 0 on success, -1 if `handle`/`key_json` is null or the JSON is
 * malformed (check `loom_last_error` for why).
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`. `key_json` must be
 * null or point to a valid, NUL-terminated UTF-8 C string for the
 * duration of this call (not retained afterwards).
 */
 int32_t loom_handle_key(struct LoomHandle *handle, const char *key_json);

/**
 * Advance background/animation state by one tick (call at whatever
 * cadence the host frontend polls at -- matches how every native tui.rs
 * drives `Shell::tick()` today).
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`.
 */
 void loom_tick(struct LoomHandle *handle);

/**
 * Render the current frame at `width`x`height` cells, returned as
 * JSON-encoded `loom_engine::render::CellGrid`. Returns null on error
 * (null handle) -- check `loom_last_error`. The returned string must be
 * freed with `loom_free_string`.
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`.
 */
 char *loom_render(struct LoomHandle *handle, uint16_t width, uint16_t height);

/**
 * True once the game has requested to quit (player selected Quit from the
 * main menu, or equivalent). The host frontend should stop its loop and
 * call `loom_save_on_exit` + `loom_destroy`.
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`.
 */
 bool loom_should_quit(struct LoomHandle *handle);

/**
 * Persist any in-progress campaign run. Call once, right before
 * `loom_destroy`, mirroring every native tui.rs's exit sequence.
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`.
 */
 void loom_save_on_exit(struct LoomHandle *handle);

/**
 * Last error message recorded by a call on this handle, or null if the
 * most recent call succeeded. The returned string must be freed with
 * `loom_free_string`.
 *
 * # Safety
 * `handle` must be a live pointer from `loom_create`.
 */
 char *loom_last_error(struct LoomHandle *handle);

/**
 * Free a string returned by `loom_render` or `loom_last_error`.
 *
 * # Safety
 * `s` must be a pointer previously returned by `loom_render` or
 * `loom_last_error` and not already freed. Passing null is safe (no-op).
 */
 void loom_free_string(char *s);

#endif  /* LOOM_ENGINE_CAPI_H */
